// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuXKd5DPWe7UB7lJEzuKpahfJs4sM6gxI',
    appId: '1:396066408474:web:8b78780871d283004069a3',
    messagingSenderId: '396066408474',
    projectId: 'dine-ease-e2337',
    authDomain: 'dine-ease-e2337.firebaseapp.com',
    storageBucket: 'dine-ease-e2337.appspot.com',
    measurementId: 'G-YXNB217L91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvxa0bqJuBWGS_5wbEpqKif-ov5mcXw8k',
    appId: '1:396066408474:android:ce12e23516fb59404069a3',
    messagingSenderId: '396066408474',
    projectId: 'dine-ease-e2337',
    storageBucket: 'dine-ease-e2337.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqQ33F3hHNH7HZ1pU5282Ud3dFKL-NN_g',
    appId: '1:396066408474:ios:f028d821b17343714069a3',
    messagingSenderId: '396066408474',
    projectId: 'dine-ease-e2337',
    storageBucket: 'dine-ease-e2337.appspot.com',
    iosClientId: '396066408474-7l19pq38bj8n734ar7msqsikfop5ipsn.apps.googleusercontent.com',
    iosBundleId: 'com.fuzail.dineease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqQ33F3hHNH7HZ1pU5282Ud3dFKL-NN_g',
    appId: '1:396066408474:ios:f028d821b17343714069a3',
    messagingSenderId: '396066408474',
    projectId: 'dine-ease-e2337',
    storageBucket: 'dine-ease-e2337.appspot.com',
    iosClientId: '396066408474-7l19pq38bj8n734ar7msqsikfop5ipsn.apps.googleusercontent.com',
    iosBundleId: 'com.fuzail.dineease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuXKd5DPWe7UB7lJEzuKpahfJs4sM6gxI',
    appId: '1:396066408474:web:76da927642d3e4474069a3',
    messagingSenderId: '396066408474',
    projectId: 'dine-ease-e2337',
    authDomain: 'dine-ease-e2337.firebaseapp.com',
    storageBucket: 'dine-ease-e2337.appspot.com',
    measurementId: 'G-4QENXPFZ0M',
  );
}
